name: Coot CI Homebrew macOS

on:
  push:

jobs:

  build-coot-for-macos:

    runs-on: macos-latest

    steps:

    - name: Which brew?
      run:  which brew

    - name: Setup homebrew
      id:   setup-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: turn on brew analytics
      run:  brew analytics on

    - name: brew update
      run:  |
        brew update
        brew upgrade

    - name: Install Coot dependencies in Homebrew
      run:  >
         brew install boost boost-python3 brewsci/bio/clipper4coot
         brewsci/bio/raster3d brewsci/bio/ssm brewsci/bio/gemmi
         dwarfutils gsl rdkit pygobject3 gtk4 glm automake
         py3cairo pygobject3

    - uses: actions/checkout@v4



