name: Coot CI Homebrew macOS

on:
  push:

jobs:

  build-coot-for-macos:

    runs-on: macos-latest

    steps:

    - name: Which brew?
      run:  which brew

    - name: Setup homebrew
      id:   setup-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: turn on brew analytics
      run:  brew analytics on

    - name: brew update
      run:  |
        brew update
        brew upgrade

    - name: Install Coot dependencies in Homebrew
      run:  >
         brew install boost boost-python3 brewsci/bio/clipper4coot
         brewsci/bio/raster3d brewsci/bio/ssm brewsci/bio/gemmi
         dwarfutils gsl rdkit pygobject3 gtk4 glm automake
         py3cairo pygobject3

    - uses: actions/checkout@v4

    - name: make directory
      run: mkdir ../build

    - name: debug dir structure
      working-directory: ../build
      run: |
        pwd
        echo ============ AA
        ls -l ..
        echo ============ BB
        ls -l
        echo ============ CC
        ls -l ../coot*

    - name: Set fftw for future use
      run: echo "fftw_prefix=/opt/homebrew/Cellar/clipper4coot/2.1.20180802_3/fftw2" >> $GITHUB_ENV

    - name: configure it
      id: configation-step
      working-directory: ../build
      run: >
         ../coot/configure
         SHELL=/bin/bash
         PYTHON=python3
         COOT_BUILD_INFO_STRING="Compiled with a GitHub action"
         --prefix="$HOME/coot"
         --with-fftw-prefix=$fftw_prefix
         --with-glm=/opt/homebrew
         --with-boost=/opt/homebrew
         --with-boost-libdir=/opt/homebrew/lib
         --with-rdkit-prefix=/opt/homebrew
         --with-guile

    - name: compile it
      id: compile-step
      working-directory: ../build
      run: make -j 4




