name: Coot CI Homebrew macOS

on:
  push:

jobs:

  build-coot-for-macos:

    runs-on: macos-latest

    steps:

    - name: Which brew?
      run:  which brew

    - name: Setup homebrew
      id:   setup-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Cache Homebrew Cellar and Cache
      uses: actions/cache@v4
      with:
        path: |
          /opt/homebrew/Cellar
          /Users/runner/Library/Caches/Homebrew
        key: brew-${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          brew-${{ runner.os }}-brew-${{ runner.os }}

    - name: turn on brew analytics
      run:  brew analytics on

    - name: brew update
      run:  |
        brew update
        brew upgrade

    - name: Install Coot dependencies in Homebrew
      run:  >
         brew install boost boost-python3 brewsci/bio/clipper4coot
         brewsci/bio/raster3d brewsci/bio/ssm brewsci/bio/gemmi
         dwarfutils gsl rdkit pygobject3 gtk4 glm automake
         py3cairo pygobject3 swig

    - uses: actions/checkout@v4

    - name: debug dir structure 1
      run: |
        pwd
        echo ============ AA
        ls -l ..

    - name: debug dir structure 2
      run: |
        pwd
        echo ============ BB
        ls -l

    - name: Set fftw for future use
      run: echo "fftw_prefix=/opt/homebrew/Cellar/clipper4coot/2.1.20180802_3/fftw2" >> $GITHUB_ENV

    - name: autogen
      id: autogen-step
      run: bash autogen-mac.sh

    - name: configure it
      id: configation-step
      run: >
         ./configure
         SHELL=/bin/bash
         PYTHON=python3
         COOT_BUILD_INFO_STRING="Compiled with a GitHub action"
         --prefix="$HOME/coot"
         --with-fftw-prefix=$fftw_prefix
         --with-glm=/opt/homebrew
         --with-boost=/opt/homebrew
         --with-boost-libdir=/opt/homebrew/lib
         --with-rdkit-prefix=/opt/homebrew
         --with-guile

    - name: compile it
      id: compile-step
      run: make -j 4

    - name: what has been made
      run: ls . src

